const enumeration = "(i.e. Item1, Item2)";

module.exports = {
    "A fast electronic calculating machine that accepts digitized input information. Processes digitized information according to the list of internally stored instructions, and produces a resulting output information.": "Digital Computer",
    [`Enumerate 4 types of Computers ${enumeration}`]: "Personal Computers, Workstations, Mainframes, Supercomputers",
    [`Enumerate 4 functional units of a Computer ${enumeration}`]:"Input Unit, Memory Unit, Processing Unit, Output Unit",
    "Accepts coded information from human operators or from other computers.":"Input Unit",
    "It is where programs are stored during their execution.":"Memory Unit",
    "Also known as the Central Processing Unit (CPU), it is composed of ALU (Arithmetic and Logic Unit) and the Control Unit (CU), 10 times faster than a Main Memory.":"Processing Unit",
    "It sends processed results to the outside world.":"Output Unit",
    "Used when large amounts of data have to be stored (on a more permanent basis), particularly if some data need to be accessed very frequently.":"Auxiliary Storage",
    [`Enumerate 4 main memory divisions ${enumeration}`]:"Input Storage Area, Working Storage Space, Output Storage Area, Program Storage Area",
    "It is the design of computers, including their Instruction Sets, Hardware Components, and System Organization.":"Computer Architecture",
    [`Enumerate 4 Types of Programming Languages ${enumeration}`]:"Machine Language, Assembly Language, High-Level Language, 4GL Language",
    [`Enumerate 3 Advantages of a High-Level Languages over Low-Level Languages ${enumeration}`]:"Easy to learn, Predefined Functions, Portability",
    [`Enumerate 3 Advantages of Low-Level Languages over a High-Level Languages ${enumeration}`]:"Compact Code, Speed, Flexible",
    // WEEK 3
    "Communicates directly within the CPU, Auxiliary memory and Cache memory.":"Main Memory",
    [`Enumerate 2 of what makes a main memory ${enumeration}`]:"RAM, ROM",
    "DRAM means":"Dynamic Random Access Memory",
    "SRAM means":"Static Random Access Memory",
    "NVRAM means":"Non-Volatile Random Access Memory",
    "The unit which performs most of the processing inside a computer. It processes all instructions received by software running on the PC and by other hardware components, and acts as a powerful calculator.":"Central Processing Unit",
    [`Enumerate 3 components of CPU ${enumeration}`]:"Arithmetic and Logic Unit, Control Unit, Register",
    "It is the collection of wires that connects several devices within a computer system.":"Bus Structure",
    [`Enumerate 3 main grouping of Lines ${enumeration}`]:"Data Bus, Address Bus, Control Bus",
    // WEEK 4
    "It stores data and measures storage in different sizes.":"Bit and Byte",
    "In 1778, Intel released the 8086 µp and a year later the 8088.":"32-bit and 64-bit processors",
    "It has a data and address bus of 32-bit each.":"32-bit processor",
    "Sixty-four-bit processors have been with us since 1992, and in the 21st century they have started to become mainstream.":"64-bit processor",
    "The address space, assigned to a logical partition, that the operating system perceives as its main storage.":"Logical Memory",
    "The actual RAM of the system, which usually takes the form of cards (DIMMs) attached onto the motherboard. Also called primary memory, it is the only storage type directly accessibly to the CPU and holds the instructions of programs to execute.":"Physical Memory",
    "They are more often used to index or point to the memory location holding the operand data for many instructions.":"Index Register and Pointer",
    "SP means":"Stack Pointer",
    "BP means":"Base Pointer",
    "SI means":"Source Index",
    "DI means":"Destination Index",
    "This contains 16-bits, but 7 of them are not used. Each bit ins the Processor Status Word is a flag. These flags are divided into the conditional flags and the control flags.":"Processor Status Word or Status Register",
    [`Enumerate 3 control flags ${enumeration}`]:"Direction Flag, Interrupt Enable Flag, Trap Flag",
    "The Main Memory can be partitioned in 64K (65, 536) byte segments where each segment represents an independently addressable unit of memory consisting of 64K consecutive byte-wide storage locations.":"Segment Registers and Memory Segmentation",
    "The 8086/8088 is identified by a segment (its base address) and an Offset.":"Logical Address"
};
