const enumeration = "(i.e. Item1, Item2)";

module.exports = {
    "Involves the use of computational, statistical and mathematical methods to obtain results.":"Quantitative Research",
    "True or False: Quantitative Research involves the use of computational, statistical and mathematical methods to obtain results.":"True",
    "True or False: One of the Key Features of Quantitative Research is - Research is used to evaluate the hypothesis andeventuallyto accept or deny it.":"True",
    [`Enumerate 8 Characteristics of Quantitative Research ${enumeration}`]:
    "LARGE SAMPLE SIZE, OBJECTIVITY, CONCISE VISUAL PRESENTATION, FASTER DATA ANALYSIS, GENERALIZED DATA, FAST AND EASY DATA COLLECTION, RELIABLE DATA, HIGH REPLICABILITY",
    "To obtain ore meaningful statisticalresult, the data must come froma largesamplesize.":"LARGE SAMPLE SIZE",
    "Data gathering and analysis of results are done accurately, objectivity, and are unaffected by the researcher’s intuition and personal guesses.":"OBJECTIVITY",
    "Data is numerical which makes presentation through graphs, charts, and tables possible and with better conveyance and interpretation.":"CONCISE VISUAL PRESENTATION",
    "The use of statistical tools gives way for a less time-consuming data analysis.":"FASTER DATA ANALYSIS",
    "True or False: LARGE SAMPLE SIZE is presentation through graphs, charts,and tables possible and with better conveyance and interpretation.":"False",
    "True or False FASTER DATA ANALYSIS is to obtain ore meaningful statistical result, the data must come froma large sample size.":"False",
    "True or False: OBJECTIVITY is data gathering and analysis of results aredone accurately, objectivity, and are unaffected by the researcher’s intuition and personal guesses.":"True",
    "Data taken from a sample can be applied to the population if sampling is done accordingly such us sufficient size and random samples were taken.":"GENERALIZED DATA",
    "Depending on the types of data needed, collection can be quick and easy.":"FAST AND EASY DATA COLLECTION",
    "Data is taken and analyzed objectively from a sample as a representative of the population, making it more credible and reliable for policymaking and decision making.":"RELIABLE DATA",
    "The quantitative method canbe repeated to verify findings enhancing its validity, free from false or immature conclusions.":"HIGH REPLICABILITY", 
    "True or False: One of the advantages of QR is it is very objective.":"True",
    "True or False: One of the disadvantages of QR is it lacks the necessary data to explore a problem or concept in depth":"True",
    [`Enumerate 5 Kinds of Quantitative Research ${enumeration}`]:
    "DESCRIPTIVE DESIGN, CORRELATIONAL DESIGN, EX POST FACTO DESIGN, QUASI-EXPERIMENTAL DESIGN, EXPERIMENTAL DESIGN",
    "used to describe a particular phenomenon by observing it as it occurs in nature.":"DESCRIPTIVE DESIGN",
    "identifies the relationship between variables.":"CORRELATIONAL DESIGN",
    "used to investigate a possible relationship between previous events and present conditions.":"EX POST FACTO DESIGN",
    "used to established the cause and effect relationship of variables.":"QUASI-EXPERIMENTAL DESIGN",
    "it uses random assignment of subjects and experimental manipulations.":"EXPERIMENTAL DESIGN",
    "the determination of the different kinds of physical activities and how often high school students do it turning the quarantine period.":"DESCRIPTIVE DESIGN",
    "the relationship between the amount of physical activity done and student academic achievement.":"CORRELATIONAL DESIGN",
    "How does the parent’s academic achievement academic achievement affect the children obesity?":"EX POST FACTO DESIGN",
    "the effects of utilizing e-learning approach in English among SHS Learners.":"QUASI-EXPERIMENTAL DESIGN",
    "a comparison of the effects of various blended learning to the reading comprehension of elementary pupils.":"EXPERIMENTAL DESIGN",
    "Advantage or Disadvantage: Very objective":"Advantage",
    "Advantage or Disadvantage: Numerical and quantifiable data can be used to predict outcomes":"Advantage",
    "Advantage or Disadvantage: Findings are generalizable to the population.":"Advantage",
    "Advantage or Disadvantage: The is conclusive establishment of cause and effect":"Advantage",
    "Advantage or Disadvantage: Fast and easy data analysis using statistical software":"Advantage",
    "Advantage or Disadvantage: Fast and easy data gathering":"Advantage",
    "Advantage or Disadvantage: Quantitative research can be replicated or repeated":"Advantage",
    "Advantage or Disadvantage: Validity and reliability can be established":"Advantage",
    "Advantage or Disadvantage: It lacks the necessary data to explore a problem or concept in depth":"Disadvantage",
    "Advantage or Disadvantage: It does not provide comprehensive explanation of human experiences":"Disadvantage",
    "Advantage or Disadvantage: Some information cannot be described by numerical data such as feelings, and beliefs":"Disadvantage",
    "Advantage or Disadvantage: The research design is rigid and not very flexible":"Disadvantage",
    "Advantage or Disadvantage: The participants are limited to choose only from the given responses.":"Disadvantage",
    "Advantage or Disadvantage: The respondents may tend to provide inaccurate responses.":"Disadvantage",
    "Advantage or Disadvantage: A large sample size makes data collection more costly.":"Disadvantage",
    "True or False: Quantitative researchers are seeking to monitor extraneous variables by performing their laboratory studies.":"True",
    "True or False: The research aims at subjectivity and is isolated from the data":"False",
    "True or False: The nature of the research shall be detected before it starts":"True",
    "True or False: The truth of the quantitative researcher is not empirical and exists independently for the researcher and is capable of being seen by everyone.":"False",
    "True or False: Research is used to evaluate the synthesis and eventually to accept or deny it.":"False"
};
